<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>Xunlei.Open.DlSdk.Native.linux-x64</PackageId>
    <Version>1.0.0</Version>
    <Authors>Xunlei</Authors>
    <Description>Xunlei.Open.DlSdk 的 Linux x64 平台动态库包。</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>NU5128</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="runtimes/linux-x64/native/libdk.so" Pack="true" PackagePath="runtimes/linux-x64/native/" />
  </ItemGroup>
</Project>
