pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'xl-dl-java'

include ':android'
include ':desktop'
include ':native:windows-x64'
include ':native:windows-x86'
include ':native:macos-universal'
include ':native:linux-x64'
