<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>Xunlei.Open.DlSdk.Native.win-x64</PackageId>
    <Version>1.0.3</Version>
    <Authors>Xunlei</Authors>
    <Description>Xunlei.Open.DlSdk 的 Windows x64 平台动态库包。</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>NU5128</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="runtimes/win-x64/native/dk.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
  </ItemGroup>
</Project>
